# Generated by Django 2.0.9 on 2019-02-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
