# Generated by Django 2.0.9 on 2019-01-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('freelancer', '0003_auto_20180905_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerpage',
            name='about_tools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
