# Generated by Django 2.0.9 on 2019-01-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelancerpage_about_tools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerpage',
            old_name='about_tools',
            new_name='programming_tools',
        ),
    ]
