# Generated by Django 2.0.9 on 2019-01-03 03:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_auto_20190103_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpage',
            name='programming_tools',
            field=wagtail.core.fields.StreamField([('programming_tools', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
