# Generated by Django 2.0.9 on 2019-01-05 02:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_auto_20190103_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerpage',
            name='title_roles',
            field=wagtail.core.fields.StreamField([('title_roles', wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
