# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-06 08:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_freelancerpage_title_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerpage',
            name='extra_head_tags',
            field=wagtail.core.fields.StreamField([('extra_head_tags', wagtail.core.blocks.StructBlock([('tag', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
