# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 23:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_auto_20190106_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerpage',
            name='mission',
            field=wagtail.core.fields.StreamField([('mission', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerpage',
            name='testimonial',
            field=wagtail.core.fields.StreamField([('testimonial', wagtail.core.blocks.StructBlock([('testimonial', wagtail.core.blocks.BlockQuoteBlock())]))], blank=True, null=True),
        ),
    ]
