# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 23:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_auto_20190112_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpage',
            name='testimonial',
            field=wagtail.core.fields.StreamField([('testimonial', wagtail.core.blocks.StructBlock([('testimonial', wagtail.core.blocks.BlockQuoteBlock()), ('author', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
