# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 01:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_auto_20190112_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpage',
            name='mission',
            field=wagtail.core.fields.StreamField([('mission', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('icon_link', wagtail.core.blocks.RawHTMLBlock(required=False)), ('img_required', wagtail.core.blocks.BooleanBlock(required=False)), ('icon_img', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerpage',
            name='portfolio',
            field=wagtail.core.fields.StreamField([('portfolio', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('intro', wagtail.core.blocks.RichTextBlock()), ('display_link', wagtail.core.blocks.BooleanBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
