# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('freelancer', '0014_auto_20190112_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerpage',
            name='website_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to='wagtailimages.Image'),
        ),
    ]
