# Generated by Django 2.0.9 on 2020-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaycoursecontacts',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='holidaycoursecontacts',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holidaycoursecontacts',
            name='student_keen',
            field=models.BooleanField(default=True),
        ),
    ]
