# Generated by Django 2.0.9 on 2020-03-25 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200324_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaycoursecontacts',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=6, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
    ]
