# Generated by Django 2.0.9 on 2020-03-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200325_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaycoursecontacts',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
