# Generated by Django 2.0.9 on 2020-03-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200327_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolidayCourseContacts',
            new_name='HolidayCourseContact',
        ),
    ]
