# Generated by Django 2.0.9 on 2020-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20200330_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaycourseinterest',
            name='referee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
