# Generated by Django 2.0.9 on 2020-04-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_holidaycourseinterest_referee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolidayCourseInterest',
            new_name='HolidayCourseInterestData',
        ),
    ]
