# Generated by Django 2.0.9 on 2020-04-07 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200406_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaycourseinterestdata',
            name='family_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holidaycourseinterestdata',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6, validators=[django.core.validators.MinValueValidator(30.0)]),
        ),
    ]
