# Generated by Django 2.0.9 on 2020-04-19 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20200407_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuneJulyHolidayCourseInterestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('student_keen', models.BooleanField(default=True)),
                ('is_student', models.BooleanField(default=True)),
                ('family_members', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, validators=[django.core.validators.MinValueValidator(30.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='HolidayCourseInterestData',
            new_name='EasterHolidayCourseInterestData',
        ),
    ]
