# Generated by Django 2.0.9 on 2020-05-30 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20200419_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junejulyholidaycourseinterestdata',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6, validators=[django.core.validators.MinValueValidator(30.0)]),
        ),
    ]
